### PR TITLE
Either doesn’t have withFilter

### PR DESCRIPTION
**Pull request by shomatan**
Fixed compile errors.
GFP(Great Functional Programmer) taught me.

### CODE REVIEW

**Comment by chaabaj** [comment]
LGTM 👍

**Comment by ben-x9** [comment]
This looks like a matter of code style. What was the compile error? 

I also don't understand the commit message. What does this have to do with `Either` or `withFilter`?

I also don't think this is easier to read: using destructuring to explicitly name tuple components is clearer that `_1` and `_2`. Also naming variables  `state1` and `state2` makes it sound like a single state that is being changed. If we must do this at least `fromState` and `toState` would be cleaner.

**Comment by chaabaj** [comment]
For destructuring in for expression you need the object to have withFilter method (that sucks). So it's just a temporary fix for now we will see tomorrow better way of doing that. Either from standard library doesn't implement withFilter.

**Comment by shomatan** [comment]
Compile errors:
```
[error] /Users/shoma/Solutions/scala-class/src/main/scala/BankingService.scala:40:39: value withFilter is not a member of Either[BankingError,(Account, Money)]
[error]       (newFromAccount, money) <- debit(from, amount)
[error]                                       ^
[error] /Users/shoma/Solutions/scala-class/src/main/scala/BankingService.scala:41:34: value withFilter is not a member of Either[BankingError,(Account, Money)]
[error]       (newToAccount, _) <- credit(to, amount)
[error]                                  ^
[error] /Users/shoma/Solutions/scala-class/src/main/scala/BankingService.scala:42:25: type mismatch;
[error]  found   : Any
[error]  required: Account
[error]     } yield Transaction(newFromAccount, newToAccount, money)
[error]                         ^
[error] /Users/shoma/Solutions/scala-class/src/main/scala/BankingService.scala:42:41: type mismatch;
[error]  found   : Any
[error]  required: Account
[error]     } yield Transaction(newFromAccount, newToAccount, money)
[error]                                         ^
[error] /Users/shoma/Solutions/scala-class/src/main/scala/BankingService.scala:42:55: type mismatch;
[error]  found   : Any
[error]  required: Money
[error]     } yield Transaction(newFromAccount, newToAccount, money)
[error]                                                       ^
[error] 5 errors found
```

@bjoyx 
Thank you for your advice.
I'm not sure about `withFilter`.
I will improve my commit message and naming from now on.

**Review by chaabaj — APPROVED** [review]

**Comment by chaabaj** [comment]
Thanks @shomatan

**Comment by chaabaj** [comment]
I find that withFilter is quite an design error since the language have pattern matching but that's only my opinion. In fact many libraries such as scalaz don't ever provide withFilter for their data types so it's basically something that mostly unusable most of the cases. for expression should only require map and flatMap in my opinion. Later we will heavily use scalaz or cats (cats have a better documentation and it's easier to read the source to study this library)

**Pull request merged**
